### ISSUE TITLE
ModuleNotFoundError: No module named 'Genbank'

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [zhangrengang/OGAP#2]
I ran pip install Genbank with no errors but still get:

OGAP.py Arabidopsis_thaliana-mt.gb -mt -o mt_out
Traceback (most recent call last):
  File "/g/data/nm31/bin/OGAP/OGAP.py", line 11, in <module>
    from lib.Database import Database
  File "/g/data/nm31/bin/OGAP/lib/Database.py", line 14, in <module>
    from Genbank import GenbankParser, format_taxon
ModuleNotFoundError: No module named 'Genbank'

**Comment by zhangrengang** [comment]
'Genbank' is a custom script in `/g/data/nm31/bin/OGAP/lib/`. You can add the path to `PYTHONPATH` at present, and I will fix it soon. The example in bash:
```
export PYTHONPATH=/g/data/nm31/bin/OGAP/lib/:$PYTHONPATH
```
